<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/ExpenseGuard.Domain/ExpenseGuard.Domain.csproj" />
    <ProjectReference Include="../../src/ExpenseGuard.Worker/ExpenseGuard.Worker.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
